export const USER_FIND_ALL_START = 'USER_FIND_ALL_START';
export const USER_FIND_ALL_OK = 'USER_FIND_ALL_OK';
export const USER_FIND_ALL_NOK = 'USER_FIND_ALL_NOK';

export const USER_FIND_BY_ID_START = 'USER_FIND_BY_ID_START';
export const USER_FIND_BY_ID_OK = 'USER_FIND_BY_ID_OK';
export const USER_FIND_BY_ID_NOK = 'USER_FIND_BY_ID_NOK';

export const USER_SAVE_START = 'USER_SAVE_START';
export const USER_SAVE_OK = 'USER_SAVE_OK';
export const USER_SAVE_NOK = 'USER_SAVE_NOK';
export const USER_SAVE_VOID = 'USER_SAVE_VOID';