export const RECIPE_FIND_ALL_START = 'RECIPE_FIND_ALL_START';
export const RECIPE_FIND_ALL_OK = 'RECIPE_FIND_ALL_OK';
export const RECIPE_FIND_ALL_NOK = 'RECIPE_FIND_ALL_NOK';

export const RECIPE_FIND_BY_ID_START = 'RECIPE_FIND_BY_ID_START';
export const RECIPE_FIND_BY_ID_OK = 'RECIPE_FIND_BY_ID_OK';
export const RECIPE_FIND_BY_ID_NOK = 'RECIPE_FIND_BY_ID_NOK';

export const RECIPE_SAVE_START = 'RECIPE_SAVE_START';
export const RECIPE_SAVE_OK = 'RECIPE_SAVE_OK';
export const RECIPE_SAVE_NOK = 'RECIPE_SAVE_NOK';
export const RECIPE_SAVE_VOID = 'RECIPE_SAVE_VOID';